[project]
name = "aiprovider-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "httpx[socks]>=0.28.1",
    "pydantic>=2.11.2",
]
